name: Deploy to Hugging Face Space
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HF: ${{ secrets.HF }}
          HF_USER: ${{ env.HF_USER }}
          SPACE: Demo
        run: git remote add space https://$HF_USER:$HF@huggingface.co/spaces/$HF_USER/$SPACE
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
          HF_USER: ${{ env.HF_USER }}
          SPACE: Demo
        run: git push --force https://$HF_USER:$HF@huggingface.co/spaces/$HF_USER/$SPACE main
